fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
#      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
      - id: autopep8
        args: ["-v", "--in-place", "--max-line-length=100"]
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3.10
        args: ["-l", "100"]
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: ["-v", "--in-place", "--remove-all-unused-imports", "--remove-unused-variables",
               "--ignore-init-module-imports"]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=100"]
  - repo: local
    hooks:
      - id: run_tests
        language: script
        name: Run tests
        entry: run_tests.sh
        stage: [ commit ]
        verbose: true